const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  platform: process.platform,
  getSystemStats: () => ipcRenderer.invoke('app:getSystemStats'),
  createNewWindow: (payload) => ipcRenderer.send('window:createNew', payload),
  getInitialState: () => ipcRenderer.invoke('window:getInitialState'),
  getVersion: () => ipcRenderer.invoke('app:getVersion'),
  openDirectory: () => ipcRenderer.invoke('dialog:openDirectory'),
  openFile: () => ipcRenderer.invoke('dialog:openFile'),
  readDir: (dirPath) => ipcRenderer.invoke('fs:readDir', dirPath),
  readFile: (filePath) => ipcRenderer.invoke('fs:readFile', filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke('fs:writeFile', filePath, content),
  mkdir: (dirPath) => ipcRenderer.invoke('fs:mkdir', dirPath),
  rename: (oldPath, newPath) => ipcRenderer.invoke('fs:rename', oldPath, newPath),
  deletePath: (targetPath) => ipcRenderer.invoke('fs:delete', targetPath),
  onUpdateAvailable: (callback) => ipcRenderer.on('update_available', (_event, ...args) => callback(...args)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update_downloaded', (_event, ...args) => callback(...args)),
  restartApp: () => ipcRenderer.send('restart_app'),
  reportIssue: () => ipcRenderer.send('app:reportIssue'),
  onMenuAction: (callback) => ipcRenderer.on('menu:action', (_event, action) => callback(action)),
  getNativeTheme: () => ipcRenderer.invoke('app:getNativeTheme'),
  onThemeUpdated: (callback) => ipcRenderer.on('theme_updated', () => callback()),
  getCustomThemePath: () => ipcRenderer.invoke('app:getCustomThemePath'),
  initCustomTheme: () => ipcRenderer.invoke('app:initCustomTheme'),
  resetCustomTheme: () => ipcRenderer.invoke('app:resetCustomTheme'),
  openInFinder: (filePath) => ipcRenderer.invoke('fs:openInFinder', filePath),
  copyFile: (filePath) => ipcRenderer.invoke('fs:copy', filePath),
  showSaveDialog: (defaultPath) => ipcRenderer.invoke('dialog:showSaveDialog', defaultPath),
  gitGetStatus: (dirPath) => ipcRenderer.invoke('git:getStatus', dirPath),
  gitStageFile: (payload) => ipcRenderer.invoke('git:stageFile', payload),
  gitUnstageFile: (payload) => ipcRenderer.invoke('git:unstageFile', payload),
  gitCommit: (payload) => ipcRenderer.invoke('git:commit', payload),
  gitGetBranches: (dirPath) => ipcRenderer.invoke('git:getBranches', dirPath),
  gitCheckoutBranch: (payload) => ipcRenderer.invoke('git:checkoutBranch', payload),
  gitCreateBranch: (payload) => ipcRenderer.invoke('git:createBranch', payload),
  gitPush: (dirPath) => ipcRenderer.invoke('git:push', dirPath),
  gitPull: (dirPath) => ipcRenderer.invoke('git:pull', dirPath),
  gitFetch: (dirPath) => ipcRenderer.invoke('git:fetch', dirPath),
  gitStash: (payload) => ipcRenderer.invoke('git:stash', payload),
  gitStashPop: (dirPath) => ipcRenderer.invoke('git:stashPop', dirPath),
  gitMerge: (payload) => ipcRenderer.invoke('git:merge', payload)
});
