const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  platform: process.platform,
  getSystemStats: () => ipcRenderer.invoke('app:getSystemStats'),
  createNewWindow: (payload) => ipcRenderer.send('window:createNew', payload),
  getInitialState: () => ipcRenderer.invoke('window:getInitialState'),
  getVersion: () => ipcRenderer.invoke('app:getVersion'),
  openDirectory: () => ipcRenderer.invoke('dialog:openDirectory'),
  openFile: () => ipcRenderer.invoke('dialog:openFile'),
  readDir: (dirPath) => ipcRenderer.invoke('fs:readDir', dirPath),
  readFile: (filePath) => ipcRenderer.invoke('fs:readFile', filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke('fs:writeFile', filePath, content),
  mkdir: (dirPath) => ipcRenderer.invoke('fs:mkdir', dirPath),
  rename: (oldPath, newPath) => ipcRenderer.invoke('fs:rename', oldPath, newPath),
  deletePath: (targetPath) => ipcRenderer.invoke('fs:delete', targetPath),
  onUpdateAvailable: (callback) => ipcRenderer.on('update_available', (_event, ...args) => callback(...args)),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update_downloaded', (_event, ...args) => callback(...args)),
  restartApp: () => ipcRenderer.send('restart_app'),
  reportIssue: () => ipcRenderer.send('app:reportIssue'),
  onMenuAction: (callback) => ipcRenderer.on('menu:action', (_event, action) => callback(action)),
  getNativeTheme: () => ipcRenderer.invoke('app:getNativeTheme'),
  onThemeUpdated: (callback) => ipcRenderer.on('theme_updated', () => callback()),
  getCustomThemePath: () => ipcRenderer.invoke('app:getCustomThemePath'),
  initCustomTheme: () => ipcRenderer.invoke('app:initCustomTheme'),
  resetCustomTheme: () => ipcRenderer.invoke('app:resetCustomTheme'),
  openInFinder: (filePath) => ipcRenderer.invoke('fs:openInFinder', filePath),
  copyFile: (filePath) => ipcRenderer.invoke('fs:copy', filePath),
  showSaveDialog: (defaultPath) => ipcRenderer.invoke('dialog:showSaveDialog', defaultPath),
  gitGetStatus: (dirPath) => ipcRenderer.invoke('git:getStatus', dirPath),
  gitStageFile: (payload) => ipcRenderer.invoke('git:stageFile', payload),
  gitUnstageFile: (payload) => ipcRenderer.invoke('git:unstageFile', payload),
  gitCommit: (payload) => ipcRenderer.invoke('git:commit', payload),
  gitGetBranches: (dirPath) => ipcRenderer.invoke('git:getBranches', dirPath),
  gitCheckoutBranch: (payload) => ipcRenderer.invoke('git:checkoutBranch', payload),
  gitCreateBranch: (payload) => ipcRenderer.invoke('git:createBranch', payload),
  gitPush: (dirPath) => ipcRenderer.invoke('git:push', dirPath),
  gitPull: (dirPath) => ipcRenderer.invoke('git:pull', dirPath),
  gitFetch: (dirPath) => ipcRenderer.invoke('git:fetch', dirPath),
  gitStash: (payload) => ipcRenderer.invoke('git:stash', payload),
  gitStashPop: (dirPath) => ipcRenderer.invoke('git:stashPop', dirPath),
  gitMerge: (payload) => ipcRenderer.invoke('git:merge', payload),
  gitGetSyncStatus: (dirPath) => ipcRenderer.invoke('git:getSyncStatus', dirPath),
  gitGetHistory: (dirPath) => ipcRenderer.invoke('git:getHistory', dirPath),
  gitGetGraph: (dirPath) => ipcRenderer.invoke('git:getGraph', dirPath),
  gitGetFileDiff: (payload) => ipcRenderer.invoke('git:getFileDiff', payload),
  gitStagePath: (payload) => ipcRenderer.invoke('git:stagePath', payload),
  gitUnstagePath: (payload) => ipcRenderer.invoke('git:unstagePath', payload),
  gitGetBlame: (payload) => ipcRenderer.invoke('git:getBlame', payload),
  gitGetConflicts: (dirPath) => ipcRenderer.invoke('git:getConflicts', dirPath),
  gitResolveConflict: (payload) => ipcRenderer.invoke('git:resolveConflict', payload),
  searchWorkspace: (payload) => ipcRenderer.invoke('fs:searchWorkspace', payload),
  terminalGetShell: () => ipcRenderer.invoke('terminal:getShell'),
  terminalExec: (payload) => ipcRenderer.invoke('terminal:exec', payload),
  terminalWriteInput: (input) => ipcRenderer.invoke('terminal:writeInput', input),
  terminalKill: () => ipcRenderer.invoke('terminal:kill'),
  onTerminalData: (callback) => ipcRenderer.on('terminal:data', (_event, data) => callback(data)),
  onTerminalExit: (callback) => ipcRenderer.on('terminal:exit', (_event, data) => callback(data)),
  terminalSpawnPty: (payload) => ipcRenderer.invoke('terminal:spawnPty', payload),
  terminalWritePty: (data) => ipcRenderer.invoke('terminal:writePty', data),
  terminalResizePty: (payload) => ipcRenderer.invoke('terminal:resizePty', payload),
  terminalKillPty: () => ipcRenderer.invoke('terminal:killPty'),
  onTerminalPtyData: (callback) => ipcRenderer.on('terminal:ptyData', (_event, data) => callback(data)),
  onTerminalPtyExit: (callback) => ipcRenderer.on('terminal:ptyExit', (_event, data) => callback(data)),
  pluginGetDir: () => ipcRenderer.invoke('plugin:getDir'),
  pluginGetInstalled: () => ipcRenderer.invoke('plugin:getInstalled'),
  pluginInstall: (payload) => ipcRenderer.invoke('plugin:install', payload),
  pluginUninstall: (pluginId) => ipcRenderer.invoke('plugin:uninstall', pluginId),
  pluginGetSecret: (payload) => ipcRenderer.invoke('plugin:getSecret', payload),
  pluginSetSecret: (payload) => ipcRenderer.invoke('plugin:setSecret', payload),
  pluginDeleteSecret: (payload) => ipcRenderer.invoke('plugin:deleteSecret', payload)
});
